### ISSUE TITLE
Full path needed for TODO_FILE_LOCATION

### ISSUE THREAD

**Issue by goshawk22** [TobyBridle/Todo#5]
For example, when `TODO_FILE_LOCATION` is set to `~/.config/todo/todo.txt,` it fails when creating a todo with 
`thread 'main' panicked at 'Could not write to file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:151:42`
When TODO_FILE_LOCATION is set to /home/adam/.config/todo/todo.txt, creating a todo works.

It might also make sense to have a default value for the file location, probably in `~/.config/todo/` or `~/.local/share/` , that is used if `TODO_FILE_LOCATION` is not set.

**Comment by TobyBridle** [comment]
~~I don't think that's an issue with the program itself but rather how environment variables work. I'm pretty sure rather than `~.config/todo/todo.txt` the correct way to do it would be using `$HOME/.config/todo/todo.txt`?~~
My bad - I was under the impression that you could not use environment variables like that. I will look into this issue and try to amend it as soon as possible.

Default file location is a good idea. It wouldn't be as simple as just setting it to `~/.config/todo/todo.todos` for example, since the program is intended to work on multiple OS. However, it still shouldn't be too big of an issue since I'm sure there are very simple ways to check for platform type in rust and change the path depending on that.

**Comment by TobyBridle** [comment]
The issue with having a full path has been resolved; however, I have realised that I forgot to implement the default path. This should be quite simple to do and so I will probably push a fix later.
